'use strict';

exports.__esModule = true;
var AWAIT_MARKER = '@@redux-await/AWAIT_MARKER';
exports.AWAIT_MARKER = AWAIT_MARKER;
var AWAIT_META_CONTAINER = '@@redux-await/AWAIT_META_CONTAINER';
exports.AWAIT_META_CONTAINER = AWAIT_META_CONTAINER;
var AWAIT_INFO_CONTAINER = '@@redux-await/AWAIT_INFO_CONTAINER';
exports.AWAIT_INFO_CONTAINER = AWAIT_INFO_CONTAINER;